name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - name: Flutter CLI
      uses: steebchen/flutter@v1.0.0
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
      working-directory: src/modules/spotify_api
    - name: Run tests
      run: flutter pub run test
      working-directory: src/modules/spotify_api
