name: Dart CI

on: 
  push:
    paths: 
      - .github/workflows/dart.yml
      - 'src/modules/spotfy_api/**'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
