name: Flutter CI

on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: src/modules/spotify_api
    - run: flutter test
      working-directory: src/modules/spotify_api
    #- run: flutter build apk
