#The name of your workflow.
name:  flutter test and build artificat
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: macos-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1.2.0
        with:
          flutter-version: '1.12.14'
          channel: 'dev'
      - run: flutter pub get
        working-directory: src
      # run static analys code
      #- run: flutter  analyze
      #  working-directory: src
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
        working-directory: src
      - run: flutter build apk --split-per-abi
        working-directory: src
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src/build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}
