name: Flutter CI

on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get
        working-directory: src/modules/spotify_api

    - name: run tests
      uses: steebchen/flutter@v1.0.0
      with:
        args: test
        working-directory: src/modules/spotify_api
